require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TwssesController do

  # This should return the minimal set of attributes required to create a valid
  # Twss. As you add validations to Twss, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all twsses as @twsses" do
      twss = Twss.create! valid_attributes
      get :index
      assigns(:twsses).should eq([twss])
    end
  end

  describe "GET show" do
    it "assigns the requested twss as @twss" do
      twss = Twss.create! valid_attributes
      get :show, :id => twss.id.to_s
      assigns(:twss).should eq(twss)
    end
  end

  describe "GET new" do
    it "assigns a new twss as @twss" do
      get :new
      assigns(:twss).should be_a_new(Twss)
    end
  end

  describe "GET edit" do
    it "assigns the requested twss as @twss" do
      twss = Twss.create! valid_attributes
      get :edit, :id => twss.id.to_s
      assigns(:twss).should eq(twss)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Twss" do
        expect {
          post :create, :twss => valid_attributes
        }.to change(Twss, :count).by(1)
      end

      it "assigns a newly created twss as @twss" do
        post :create, :twss => valid_attributes
        assigns(:twss).should be_a(Twss)
        assigns(:twss).should be_persisted
      end

      it "redirects to the created twss" do
        post :create, :twss => valid_attributes
        response.should redirect_to(Twss.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved twss as @twss" do
        # Trigger the behavior that occurs when invalid params are submitted
        Twss.any_instance.stub(:save).and_return(false)
        post :create, :twss => {}
        assigns(:twss).should be_a_new(Twss)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Twss.any_instance.stub(:save).and_return(false)
        post :create, :twss => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested twss" do
        twss = Twss.create! valid_attributes
        # Assuming there are no other twsses in the database, this
        # specifies that the Twss created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Twss.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => twss.id, :twss => {'these' => 'params'}
      end

      it "assigns the requested twss as @twss" do
        twss = Twss.create! valid_attributes
        put :update, :id => twss.id, :twss => valid_attributes
        assigns(:twss).should eq(twss)
      end

      it "redirects to the twss" do
        twss = Twss.create! valid_attributes
        put :update, :id => twss.id, :twss => valid_attributes
        response.should redirect_to(twss)
      end
    end

    describe "with invalid params" do
      it "assigns the twss as @twss" do
        twss = Twss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Twss.any_instance.stub(:save).and_return(false)
        put :update, :id => twss.id.to_s, :twss => {}
        assigns(:twss).should eq(twss)
      end

      it "re-renders the 'edit' template" do
        twss = Twss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Twss.any_instance.stub(:save).and_return(false)
        put :update, :id => twss.id.to_s, :twss => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested twss" do
      twss = Twss.create! valid_attributes
      expect {
        delete :destroy, :id => twss.id.to_s
      }.to change(Twss, :count).by(-1)
    end

    it "redirects to the twsses list" do
      twss = Twss.create! valid_attributes
      delete :destroy, :id => twss.id.to_s
      response.should redirect_to(twsses_url)
    end
  end

end
